### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by matanki-saito** [matanki-saito/CK2JPModAppendixIII#1]
称号だけを除外する？

**Comment by Test-of-gource** [comment]
除外する必要のあるもの
`PROV<番号>`：プロビ/伯爵号
`c_`：伯爵号（インドのプロビについては定義されている？）
`e_`：帝国号
`k_`：王号
`d_`：公爵号
`b_`：男爵/都市/寺院号
及びそれらの形容詞型<称号名>_adj（伯爵号についてはc_なんちゃら_adj、男爵号については定義されていない？）

**Comment by matanki-saito** [comment]
_adjはマップに関係しますか？

**Comment by matanki-saito** [comment]
とりあえず↑の仕様で作ってみます

**Comment by matanki-saito** [comment]
done
